# Site Settings
title: Kevin's Resume
url: 'https://kevinms.github.io'
baseurl: '/' #change it according to your repository name
#about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Kevin M. Smith
tagline: Software Engineer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Seeking a challenging full time position in the field of Computer Science applying problem solving and team skills.'

#sidebar links
email: ksmith.nop@gmail.com
phone: 012 345 6789
website: blog.example.com #do not add http://
linkedin: kevin-smith-936992b # https://www.linkedin.com/in/kevin-smith-9369992b/
github: kevinms
#twitter: '@kevinms'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
education_in_main: True

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
